name: 🐛 Bug Report
description: Use this template to report a bug you discovered.
title: "A short name to describe the bug."
labels: [Bug]
body:
  - type: checkboxes
    attributes:
      label: The following checks have been done.
      description: Please go through the list and make sure you did each step.
      options:
        - label: I could not find another bug report that covers what I discovered.
          required: true
        - label: This report does not request new features or enhancements.
          required: true
  - type: textarea
    attributes:
      label: What is the current behavior?
      description: Please provide a clear and concise description of what the bug is currently doing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is the expected behavior?
      description: Please provide a clear and concise description of what should be happening.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Some additional context.
      description: If you have links, screenshots, or other thoughts, please include them here.
    validations:
      required: false
